import math

x = 2
y = 10

print('Valor absoluto')
print(math.fabs(x))
print('--------------------------------------------')
print('Teto')
print(math.floor(x))
print('--------------------------------------------')
print('Piso')
print(math.ceil(x))
print('--------------------------------------------')
print('Raiz quadrada')
print(math.sqrt(x))
print('--------------------------------------------')
print('Parte inteira')
print(math.trunc(x))
print('--------------------------------------------')
print('Fatorial')
print(math.factorial(y))
print('--------------------------------------------')

print('Seno')
print(math.sin(x))
print('--------------------------------------------')
print('Cosseno')
print(math.cos(x))
print('--------------------------------------------')
print('Tangente')
print(math.tan(x))
print('--------------------------------------------')
print('Arco-seno')
print(math.asin(1))
print('--------------------------------------------')
print('Arco-tangente')
print(math.atan(x))
print('--------------------------------------------')
print('Arco-cosseno')
print(math.hypot(x,y))
print('--------------------------------------------')
print('Logaritmo')
print(math.log(x, y))
print('--------------------------------------------')
print('PI')
print(math.pi)
